name       : python-pytoolconfig
version    : 1.2.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pytoolconfig/pytoolconfig-1.2.4.tar.gz : 5e1a246f77970ddb5f3d8d06fbf162424b8a1adfc22c2eb51826b383bf293d1e
homepage   : https://github.com/bageljrkhanofemus/pytoolconfig
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python tool configuration
description: |
    The goal of this project is to manage configuration for python tools, such as black and rope and add support for a pyproject.toml configuration file.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-pdm-pep517
build      : |
    %python3_setup
install    : |
    %python3_install
